<?php
/**
 * Административный файл с настройками модуля
 *
 * @author  Linemedia
 * @since   01/08/2012
 *
 * @link    http://auto.linemedia.ru/
 */

$LM_AUTO_ANALOGSSIMPLE_COMMON_SEARCH_TECDOC = (string) $_POST['LM_AUTO_ANALOGSSIMPLE_COMMON_SEARCH_TECDOC'];
COption::SetOptionString($sModuleId, 'LM_AUTO_ANALOGSSIMPLE_COMMON_SEARCH_TECDOC', $LM_AUTO_ANALOGSSIMPLE_COMMON_SEARCH_TECDOC);

$LM_AUTO_ANALOGSSIMPLE_USE_RECURSIVE_SEARCH = (string) $_POST['LM_AUTO_ANALOGSSIMPLE_USE_RECURSIVE_SEARCH'];
COption::SetOptionString($sModuleId, 'LM_AUTO_ANALOGSSIMPLE_USE_RECURSIVE_SEARCH', $LM_AUTO_ANALOGSSIMPLE_USE_RECURSIVE_SEARCH);

$LM_AUTO_ANALOGSSIMPLE_RECURSIVE_SEARCH_COUNTS = (int) $_POST['LM_AUTO_ANALOGSSIMPLE_RECURSIVE_SEARCH_COUNTS'];
COption::SetOptionString( $sModuleId, 'LM_AUTO_ANALOGSSIMPLE_RECURSIVE_SEARCH_COUNTS', $LM_AUTO_ANALOGSSIMPLE_RECURSIVE_SEARCH_COUNTS);

$LM_AUTO_ANALOGSSIMPLE_SEARCH_OEM_CROSSES_SOUGHT = (string) $_POST['LM_AUTO_ANALOGSSIMPLE_SEARCH_OEM_CROSSES_SOUGHT'];
COption::SetOptionString($sModuleId, 'LM_AUTO_ANALOGSSIMPLE_SEARCH_OEM_CROSSES_SOUGHT', $LM_AUTO_ANALOGSSIMPLE_SEARCH_OEM_CROSSES_SOUGHT);

