<?php

$LM_AUTO_BRANCHES_COMMON_REGISTER_BRANCH_PARAM = (string) $_POST['LM_AUTO_GARAGE_DEMO_FOLDER'];
COption::SetOptionString($sModuleId, 'LM_AUTO_GARAGE_DEMO_FOLDER', $LM_AUTO_BRANCHES_COMMON_REGISTER_BRANCH_PARAM);
