<?
$PERM["obrabotka-vin"]["*"]="D";
$PERM["obrabotka-vin"]["G12"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["catalog"]["G6"]="W";
$PERM["catalog"]["*"]="R";
$PERM["log.txt"]["2"]="D";
$PERM["log.txt"]["3"]="D";
$PERM["log.txt"]["4"]="D";
$PERM["personal"]["2"]="D";
$PERM["personal"]["6"]="W";
$PERM["articles"]["6"]="W";
$PERM["news"]["6"]="W";
$PERM["about"]["6"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>