<?php

$LM_AUTO_SUPPLIERS_XLS_TYPE = (string) $_POST['LM_AUTO_SUPPLIERS_XLS_TYPE'];
COption::SetOptionString($sModuleId, 'LM_AUTO_SUPPLIERS_XLS_TYPE', $LM_AUTO_SUPPLIERS_XLS_TYPE);


$LM_AUTO_SUPPLIERS_EXPORT_ORIGINAL_ARTICLES = (string) $_POST['LM_AUTO_SUPPLIERS_EXPORT_ORIGINAL_ARTICLES'];
COption::SetOptionString($sModuleId, 'LM_AUTO_SUPPLIERS_EXPORT_ORIGINAL_ARTICLES', $LM_AUTO_SUPPLIERS_EXPORT_ORIGINAL_ARTICLES);


$LM_AUTO_SUPPLIERS_REQUESTED_FIRST_STATUSES = (array) $_POST['LM_AUTO_SUPPLIERS_REQUESTED_FIRST_STATUSES'];
COption::SetOptionString($sModuleId, 'FIRST_STATUSES', serialize($LM_AUTO_SUPPLIERS_REQUESTED_FIRST_STATUSES));


$LM_AUTO_SUPPLIERS_REQUESTED_GOODS_STATUS = (string) $_POST['LM_AUTO_SUPPLIERS_REQUESTED_GOODS_STATUS'];
COption::SetOptionString($sModuleId, 'REQUESTED_GOODS_STATUS', $LM_AUTO_SUPPLIERS_REQUESTED_GOODS_STATUS);


$LM_AUTO_SUPPLIERS_CLOSED_STATUSES = (array) $_POST['LM_AUTO_SUPPLIERS_CLOSED_STATUSES'];
COption::SetOptionString($sModuleId, 'CLOSED_STATUSES', serialize($LM_AUTO_SUPPLIERS_CLOSED_STATUSES));
