<?php

$LM_AUTO_MAIN_EXPERIMENTAL_ORDER_SPLIT = $_POST['LM_AUTO_MAIN_EXPERIMENTAL_ORDER_SPLIT'] == 'Y' ? 'Y' : 'N';
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_EXPERIMENTAL_ORDER_SPLIT', $LM_AUTO_MAIN_EXPERIMENTAL_ORDER_SPLIT);

$LM_AUTO_MAIN_EXPERIMENTAL_ORDER_LIST = $_POST['LM_AUTO_MAIN_EXPERIMENTAL_ORDER_LIST'] == 'Y' ? 'Y' : 'N';
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_EXPERIMENTAL_ORDER_LIST', $LM_AUTO_MAIN_EXPERIMENTAL_ORDER_LIST);

$LM_AUTO_MAIN_EXPERIMENTAL_ORM_SEARCH = $_POST['LM_AUTO_MAIN_EXPERIMENTAL_ORM_SEARCH'] == 'Y' ? 'Y' : 'N';
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_EXPERIMENTAL_ORM_SEARCH', $LM_AUTO_MAIN_EXPERIMENTAL_ORM_SEARCH);