<?php
$LM_AUTO_MAIN_CHANGE_STATUS_AFTER_PAY = (string) $_POST['LM_AUTO_MAIN_CHANGE_STATUS_AFTER_PAY'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_CHANGE_STATUS_AFTER_PAY', $LM_AUTO_MAIN_CHANGE_STATUS_AFTER_PAY);

$LM_AUTO_MAIN_STATUS_ID_AFTER_PAY = (string) $_POST['LM_AUTO_MAIN_STATUS_ID_AFTER_PAY'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_ID_AFTER_PAY', $LM_AUTO_MAIN_STATUS_ID_AFTER_PAY);

$LM_AUTO_MAIN_CANCEL_STATUS_ID = (string) $_POST['LM_AUTO_MAIN_CANCEL_STATUS_ID'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_CANCEL_STATUS_ID', $LM_AUTO_MAIN_CANCEL_STATUS_ID);
$LM_AUTO_MAIN_CANCEL_ON_STATUS = (string) $_POST['LM_AUTO_MAIN_CANCEL_ON_STATUS'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_CANCEL_ON_STATUS', $LM_AUTO_MAIN_CANCEL_ON_STATUS);

$LM_AUTO_MAIN_STATUS_USER_CANCEL_ACCESS_LIST = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_USER_CANCEL_ACCESS_LIST']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_USER_CANCEL_ACCESS_LIST', $LM_AUTO_MAIN_STATUS_USER_CANCEL_ACCESS_LIST);

$LM_AUTO_MAIN_USER_CANCEL_REASON = (string) $_POST['LM_AUTO_MAIN_USER_CANCEL_REASON'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_USER_CANCEL_REASON', $LM_AUTO_MAIN_USER_CANCEL_REASON);

$LM_AUTO_MAIN_STATUS_CHANGE_SUPPLIER_ACCESS_LIST = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_CHANGE_SUPPLIER_ACCESS_LIST']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_CHANGE_SUPPLIER_ACCESS_LIST', $LM_AUTO_MAIN_STATUS_CHANGE_SUPPLIER_ACCESS_LIST);

$LM_AUTO_MAIN_STATUS_NOTIFY_EMAIL_DEFAULT = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_NOTIFY_EMAIL_DEFAULT']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_NOTIFY_EMAIL_DEFAULT', $LM_AUTO_MAIN_STATUS_NOTIFY_EMAIL_DEFAULT);

$LM_AUTO_MAIN_TICKET_NOT_FOUND_STATUS_ID = (string) $_POST['LM_AUTO_MAIN_TICKET_NOT_FOUND_STATUS_ID'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_TICKET_NOT_FOUND_STATUS_ID', $LM_AUTO_MAIN_TICKET_NOT_FOUND_STATUS_ID);

$LM_AUTO_MAIN_STATUS_REQUIRE_COMMENT = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_REQUIRE_COMMENT']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_REQUIRE_COMMENT', $LM_AUTO_MAIN_STATUS_REQUIRE_COMMENT);

$LM_AUTO_MAIN_CANCEL_REQUIRE_COMMENT = (string) $_POST['LM_AUTO_MAIN_CANCEL_REQUIRE_COMMENT'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_CANCEL_REQUIRE_COMMENT', $LM_AUTO_MAIN_CANCEL_REQUIRE_COMMENT);

//Статус, по которому отгружать заказы
$LM_AUTO_MAIN_STATUS_TO_UNLOAD = (array) $_POST['LM_AUTO_MAIN_STATUS_TO_UNLOAD']["0"];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_TO_UNLOAD', $LM_AUTO_MAIN_STATUS_TO_UNLOAD["0"]);

$LM_AUTO_MAIN_STATUS_SEND_EMAIL_FORBIDDEN = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_SEND_EMAIL_FORBIDDEN']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_SEND_EMAIL_FORBIDDEN', $LM_AUTO_MAIN_STATUS_SEND_EMAIL_FORBIDDEN);