<?php

$LM_AUTO_MAIN_STATUS_USER_RETURN = (string) $_POST['LM_AUTO_MAIN_STATUS_USER_RETURN'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_USER_RETURN', $LM_AUTO_MAIN_STATUS_USER_RETURN);

$LM_AUTO_MAIN_STATUS_MONEY_BACK = (string) $_POST['LM_AUTO_MAIN_STATUS_MONEY_BACK'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_MONEY_BACK', $LM_AUTO_MAIN_STATUS_MONEY_BACK);

$LM_AUTO_MAIN_STATUS_SHOP_MONEY_BACK = (string) $_POST['LM_AUTO_MAIN_STATUS_SHOP_MONEY_BACK'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_SHOP_MONEY_BACK', $LM_AUTO_MAIN_STATUS_SHOP_MONEY_BACK);

$LM_AUTO_MAIN_STATUS_USER_CAN_RETURN_LIST = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_USER_CAN_RETURN_LIST']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_USER_CAN_RETURN_LIST', $LM_AUTO_MAIN_STATUS_USER_CAN_RETURN_LIST);

