<?php
$LM_AUTO_MAIN_STATUS_GROUP_1_PAYED = (string) ($_POST['LM_AUTO_MAIN_STATUS_GROUP_1_PAYED']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_1_PAYED', $LM_AUTO_MAIN_STATUS_GROUP_1_PAYED);

$LM_AUTO_MAIN_STATUS_GROUP_1_CANCELED = (string) $_POST['LM_AUTO_MAIN_STATUS_GROUP_1_CANCELED'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_1_CANCELED', $LM_AUTO_MAIN_STATUS_GROUP_1_CANCELED);

$LM_AUTO_MAIN_STATUS_GROUP_1_LIST = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_GROUP_1_LIST']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_1_LIST', $LM_AUTO_MAIN_STATUS_GROUP_1_LIST);


$LM_AUTO_MAIN_STATUS_GROUP_2_PAYED = (string) ($_POST['LM_AUTO_MAIN_STATUS_GROUP_2_PAYED']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_2_PAYED', $LM_AUTO_MAIN_STATUS_GROUP_2_PAYED);

$LM_AUTO_MAIN_STATUS_GROUP_2_CANCELED = (string) $_POST['LM_AUTO_MAIN_STATUS_GROUP_2_CANCELED'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_2_CANCELED', $LM_AUTO_MAIN_STATUS_GROUP_2_CANCELED);

$LM_AUTO_MAIN_STATUS_GROUP_2_LIST = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_GROUP_2_LIST']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_2_LIST', $LM_AUTO_MAIN_STATUS_GROUP_2_LIST);


$LM_AUTO_MAIN_STATUS_GROUP_3_PAYED = (string) ($_POST['LM_AUTO_MAIN_STATUS_GROUP_3_PAYED']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_3_PAYED', $LM_AUTO_MAIN_STATUS_GROUP_3_PAYED);

$LM_AUTO_MAIN_STATUS_GROUP_3_CANCELED = (string) $_POST['LM_AUTO_MAIN_STATUS_GROUP_3_CANCELED'];
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_3_CANCELED', $LM_AUTO_MAIN_STATUS_GROUP_3_CANCELED);

$LM_AUTO_MAIN_STATUS_GROUP_3_LIST = serialize((array) $_POST['LM_AUTO_MAIN_STATUS_GROUP_3_LIST']);
COption::SetOptionString($sModuleId, 'LM_AUTO_MAIN_STATUS_GROUP_3_LIST', $LM_AUTO_MAIN_STATUS_GROUP_3_LIST);

