<?php$LM_AUTO_WHOLESALE_STATUS = (string) $_POST['LM_AUTO_WHOLESALE_STATUS'];
COption::SetOptionString($sModuleId, 'LM_AUTO_WHOLESALE_STATUS', $LM_AUTO_WHOLESALE_STATUS);$LM_AUTO_WHOLESALE_GROUP = (int) $_POST['LM_AUTO_WHOLESALE_GROUP'];
COption::SetOptionInt($sModuleId, 'LM_AUTO_WHOLESALE_GROUP', $LM_AUTO_WHOLESALE_GROUP);$LM_AUTO_WHOLESALE_PERSON = (int) $_POST['LM_AUTO_WHOLESALE_PERSON'];
COption::SetOptionInt($sModuleId, 'LM_AUTO_WHOLESALE_PERSON', $LM_AUTO_WHOLESALE_PERSON);$LM_AUTO_WHOLESALE_PAYSYSTEM = (int) $_POST['LM_AUTO_WHOLESALE_PAYSYSTEM'];
COption::SetOptionInt($sModuleId, 'LM_AUTO_WHOLESALE_PAYSYSTEM', $LM_AUTO_WHOLESALE_PAYSYSTEM);